### ISSUE TITLE
Issues from JIRA autocompletion and association with tasks problem

### ISSUE THREAD

**Issue by Kudlaty01** [gsobczyk/hamster#28]
When the category field was `customfield_10000` a task name has been completed with that field's value, but that was not the field intended to be used by me and contained some strange data..
When changed it to `project`, On filling the task name instead of autocompletion from JIRA issues I get the following
> /usr/lib/python2.7/dist-packages/hamster/widgets/activityentry.py:323:
 Warning: Source ID 373 was not found when attempting to remove it
  gobject.source_remove(self.timeout_id)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/hamster/widgets/activityentry.py", line 328, in _populate_and_show
    self.populate_suggestions()
  File "/usr/lib/python2.7/dist-packages/hamster/widgets/activityentry.py", line 236, in populate_suggestions
    self.external_activities = runtime.storage.get_ext_activities(fact.activity)
  File "/usr/lib/python2.7/dist-packages/hamster/client.py", line 148, in get_ext_activities
    return self._to_dict(('name', 'category'), self.conn.GetExtActivities(search))
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 751, in _message_cb
    _method_reply_return(connection, message, method_name, signature, *retval)
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 254, in _method_reply_return
    reply.append(signature=signature, *retval)
TypeError: Expected a string or unicode object

and nothing happens.
I have figured out that only autocompleted tasks can be reported as worklogs and that prevents me from sending anything to JIRA at all.
All my `project` fields consist mostly from two capital letters which are not completed.
Is it possible that it may have something with dbus?

**Comment by Kudlaty01** [comment]
I have figured out that `project` issue field is a complex object and it's `key` field is what is interesting me, but inserting it into configuration with dot as `project.key` won't work, as it is passed as a string to jira issue search conditions. Unfortunately, as a Jira Cloud user I am not able to set customfields.
Is there any possibility to work it around?
