### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by ghost** [gsobczyk/hamster#40]
Hello @gsobczyk ! Thank you for your efforts to support and contribute to hamster, really important program for me. However can't properly install/run your version. Log: 

pgess@laptop:/opt/hamster> hamster
ERROR:dbus.proxies:Introspect error on :1.179:/org/gnome/Hamster: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying

Traceback (most recent call last):
  File "/usr/bin/hamster", line 374, in <module>
    hamster_client.today()
  File "/usr/bin/hamster", line 136, in today
    app = today.DailyView()
  File "/usr/lib/python2.7/site-packages/hamster/today.py", line 45, in __init__
    self.create_hamster_window()
  File "/usr/lib/python2.7/site-packages/hamster/today.py", line 108, in create_hamster_window
    self.new_tags = widgets.TagsEntry()
  File "/usr/lib/python2.7/site-packages/hamster/widgets/tags.py", line 65, in __init__
    self.populate_suggestions()
  File "/usr/lib/python2.7/site-packages/hamster/widgets/tags.py", line 152, in populate_suggestions
    self.tags = self.tags or [tag["name"] for tag in runtime.storage.get_tags(only_autocomplete=True)]
  File "/usr/lib/python2.7/site-packages/hamster/client.py", line 156, in get_tags
    return self._to_dict(('id', 'name', 'autocomplete'), self.conn.GetTags(only_autocomplete))
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.179 was not provided by any .service files

pgess@laptop:/opt/hamster> /usr/lib/hamster-time-tracker/hamster-service
hamster-service up
Traceback (most recent call last):
  File "/usr/lib/hamster-time-tracker/hamster-service", line 310, in <module>
    storage = Storage(loop)
  File "/usr/lib/hamster-time-tracker/hamster-service", line 50, in __init__
    db.Storage.__init__(self, _("Unsorted"))
  File "/usr/lib/python2.7/site-packages/hamster/db.py", line 101, in __init__
    self.run_fixtures()
  File "/usr/lib/hamster-time-tracker/hamster-service", line 65, in run_fixtures
    super(Storage, self).run_fixtures()
  File "/usr/lib/python2.7/site-packages/hamster/db.py", line 1030, in run_fixtures
    self.execute("""ALTER TABLE facts ADD COLUMN exported bool default false""")
  File "/usr/lib/python2.7/site-packages/hamster/db.py", line 968, in execute
    cur.execute(state, param)
**sqlite3.OperationalError: Cannot add a column with non-constant default**

Any advices?

**Comment by gsobczyk** [comment]
1. try find files which have root as a owner
2. check if schema is properly installed
2. try to install manually schema

**Comment by gsobczyk** [comment]
closed because of inactivity

Please try new version
